### ISSUE TITLE
Typo in DeepLabV3+ with 16 output stride

### ISSUE THREAD

**Issue by stdbreaks** [JanMarcelKezmann/TensorFlow-Advanced-Segmentation-Models#16]
I suppose it must be output_layers = output_layers[:4]

https://github.com/JanMarcelKezmann/TensorFlow-Advanced-Segmentation-Models/blob/45edd430a9a6852cae474ebf3900284235a1710f/tensorflow_advanced_segmentation_models/models/DeepLabV3plus.py#L31

**Comment by JanMarcelKezmann** [comment]
Hi @stdbreaks ,

thank you for pointing it out, I have already pushed a fix.
