### ISSUE TITLE
performance of your model?

### ISSUE THREAD

**Issue by Anikily** [JanMarcelKezmann/TensorFlow-Advanced-Segmentation-Models#7]
Could you provide trained models on segmentation datasets and the comparison of these models?

**Comment by JanMarcelKezmann** [comment]
Hi, I would really like to, but I only have trained the examples you can find <a href="https://github.com/JanMarcelKezmann/TensorFlow-Advanced-Segmentation-Models/tree/master/examples">here</a> and unfortunately I do not have a GPU and the ones that are online available are not sufficient for training segmentation models on larger (benchmark) datasets.
Therefore I am not able to provide you with a comparison of the models.
Anyway from my experience and tests I have made, I can tell you that the Dual Attention Network is for example one that performs really well.
